### ISSUE TITLE
countries return  "Error": "Bad Content-Type or charset, expected 'application/json'"

### ISSUE THREAD

**Issue by jixieshi999** [ant0ine/go-json-rest-examples#14]
run command :
```
D:\GOPATH\src>curl -i -H 'Content-Type: application/json'     -d '{"Name":"Antoi
ne"}' http://127.0.0.1:8080/users
```
it return 
 "Error": "Bad Content-Type or charset, expected 'application/json'"

**Comment by ant0ine** [comment]
I can't reproduce, I'm running the example with `go run users/main.go`
and I get this:

```
curl -i -H 'Content-Type: application/json' -d '{"Name":"Antoine"}' http://127.0.0.1:8080/users
HTTP/1.1 200 OK
Content-Type: application/json
X-Powered-By: go-json-rest
Date: Wed, 27 May 2015 07:01:46 GMT
Content-Length: 36

{
  "Id": "0",
  "Name": "Antoine"
}
````

**Comment by yeahia2508** [comment]
If you are a windows user then this problem will be happen..
run this command:
curl -i -H "Content-Type: application/json"     -d "{/"Name/":/"Antoi
ne/"}" http://127.0.0.1:8080/users
Hope this will work...
