### ISSUE TITLE
Gorm example showing: cannot assign *gorm.DB to i.DB (type gorm.DB) in multiple assignment

### ISSUE THREAD

**Issue by yeahia2508** [ant0ine/go-json-rest-examples#19]
In Gorm example struct `Impl` is like this:
```
type Impl struct {
	DB gorm.DB
}
```
 but bellow line causing this error:
`i.DB, err = gorm.Open("mysql", "root:@/gorm?charset=utf8&parseTime=True")`

gorm.Open return *DB so Impl struct should be like this right? : 
```
type Impl struct {
	DB *gorm.DB
}
```

**Comment by ant0ine** [comment]
Indeed, it looks like the Gorm API has changes. I'm fixing the example. Thanks for reporting!

**Comment by ant0ine** [comment]
done
